apiVersion: v1
kind: ConfigMap
metadata:
  name: owl-scheduler-config
  namespace: owl-scheduler-system
  labels:
    app.kubernetes.io/name: owl-scheduler
    app.kubernetes.io/part-of: owl-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      retryPeriod: 2s
      resourceLock: leases
      resourceNamespace: owl-scheduler-system
      resourceName: owl-scheduler
    profiles:
      - schedulerName: owl-scheduler
        plugins:
          preFilter:
            enabled:
              - name: NodeResourcesFit
              - name: NodePorts
              - name: InterPodAffinity
          filter:
            enabled:
              - name: NodeResourcesFit
              - name: NodePorts
              - name: NodeAffinity
              - name: InterPodAffinity
              - name: TaintToleration
          postFilter:
            enabled:
              - name: DefaultPreemption
          score:
            enabled:
              - name: NodeResourcesFit
                weight: 1
              - name: InterPodAffinity
                weight: 1
              - name: NodeAffinity
                weight: 1
              - name: ImageLocality
                weight: 1
          reserve:
            enabled:
              - name: VolumeBinding
          preScore:
            enabled:
              - name: InterPodAffinity
              - name: TaintToleration
          bind:
            enabled:
              - name: DefaultBinder
        pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: MostAllocated
                resources:
                  - name: cpu
                    weight: 1
                  - name: memory
                    weight: 1
          - name: InterPodAffinity
            args:
              hardPodAffinityWeight: 1
          - name: NodeAffinity
            args:
              addedAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/os
                          operator: In
                          values:
                            - linux
