{{- /*
  Optional Prometheus ServiceMonitor
*/}}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "k8s-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-scheduler.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-scheduler.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
